import { beforeEach, describe, expect, it, vi } from "vitest";
import { hashParticipantPassword } from "./security";
import type { XifadoData } from "@shared/xifado";

const TEST_MASTER_CODE = process.env.XIFADO_MASTER_CODE ?? "test-master-code";
const TEST_PARTICIPANT_PASSWORD = "participant-test-password";
const state: XifadoData = { schedule: { start: "2026-01-01T00:00:00-03:00", end: "2026-12-31T23:59:00-03:00" }, members: { Ana: { eliminated: false, timestamp: null, reason: "", rank: null, duration: null, sessionVersion: 1, active: true, lossHistory: [] } }, credentials: {}, penalties: [], rules: [] };
const req = { headers: {} as Record<string, string> };
const res = { cookie: vi.fn((name: string, value: string) => { req.headers.cookie = `${name}=${value}`; }), clearCookie: vi.fn((name: string) => { req.headers.cookie = (req.headers.cookie ?? "").replace(new RegExp(`${name}=[^;]+;?`), ""); }) };

vi.mock("./db", () => ({ getXifadoState: vi.fn(async () => state),   saveXifadoState: vi.fn(async (next: XifadoData) => { Object.assign(state, next); return next; }),
  mutateXifadoState: vi.fn(async (mutator: (data: XifadoData) => Promise<XifadoData> | XifadoData) => { const next = await mutator(structuredClone(state)); Object.assign(state, next); return next; }) }));
const { appRouter } = await import("./routers");
const caller = appRouter.createCaller({ req: req as never, res: res as never, user: null });

describe("Xifado route authorization", () => {
  beforeEach(async () => { state.members = { Ana: { eliminated: false, timestamp: null, reason: "", rank: null, duration: null, sessionVersion: 1, active: true, lossHistory: [] } }; state.credentials = { Ana: await hashParticipantPassword(TEST_PARTICIPANT_PASSWORD) }; state.penalties = []; state.rules = []; state.schedule = { start: "2026-01-01T00:00:00-03:00", end: "2026-12-31T23:59:00-03:00" }; req.headers = {}; res.cookie.mockClear(); res.clearCookie.mockClear(); });

  it("accepts the master code only on the server and sets a cookie", async () => { await expect(caller.xifado.master.verify({ username: "mestre", masterCode: TEST_MASTER_CODE })).resolves.toMatchObject({ success: true }); expect(res.cookie).toHaveBeenCalled(); await expect(caller.xifado.master.verify({ username: "mestre", masterCode: "errado" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("declares a loss with a participant cookie and revives only with master access", async () => { await caller.xifado.participantLogin({ name: "Ana", password: TEST_PARTICIPANT_PASSWORD }); await caller.xifado.declareLossSession({ timestamp: Date.now(), reason: "teste controlado" }); expect(state.members.Ana.eliminated).toBe(true); req.headers = {}; await expect(caller.xifado.master.revive({ name: "Ana" })).rejects.toMatchObject({ code: "UNAUTHORIZED" }); await caller.xifado.master.verify({ username: "mestre", masterCode: TEST_MASTER_CODE }); await caller.xifado.master.revive({ name: "Ana" }); expect(state.members.Ana.eliminated).toBe(false); expect(state.members.Ana.lossHistory?.length).toBe(2); });
  it("removes a participant permanently and revokes the participant session", async () => { state.members.Bruno = { eliminated: false, timestamp: null, reason: "", rank: null, duration: null, sessionVersion: 1, active: true, lossHistory: [] }; await caller.xifado.participantLogin({ name: "Ana", password: TEST_PARTICIPANT_PASSWORD }); await caller.xifado.master.verify({ username: "mestre", masterCode: TEST_MASTER_CODE }); await caller.xifado.master.removeMember({ name: "Ana" }); expect(state.members.Ana).toBeUndefined(); expect(state.credentials.Ana).toBeUndefined(); await expect(caller.xifado.declareLossSession({ timestamp: Date.now() })).rejects.toMatchObject({ code: "UNAUTHORIZED" }); });
  it("rejects plaintext credentials and accepts only one named credential", async () => { state.credentials.Ana = TEST_PARTICIPANT_PASSWORD; await expect(caller.xifado.participantLogin({ name: "Ana", password: TEST_PARTICIPANT_PASSWORD })).rejects.toMatchObject({ code: "UNAUTHORIZED" }); state.credentials.Ana = await hashParticipantPassword(TEST_PARTICIPANT_PASSWORD); await expect(caller.xifado.participantLogin({ name: "Ana", password: "wrong" })).rejects.toMatchObject({ code: "UNAUTHORIZED" }); });
  it("covers the protected master management operations", async () => { await caller.xifado.master.verify({ username: "mestre", masterCode: TEST_MASTER_CODE }); const penalty = await caller.xifado.master.addPenalty({ text: "Prenda coletiva" }); const penaltyId = penalty.penalties[0].id; await caller.xifado.master.editPenalty({ id: penaltyId, text: "Prenda coletiva atualizada" }); await caller.xifado.master.togglePenalty({ id: penaltyId }); await caller.xifado.master.removePenalty({ id: penaltyId }); const rule = await caller.xifado.master.addRule({ text: "Regra principal" }); const ruleId = rule.rules[0].id; await caller.xifado.master.editRule({ id: ruleId, text: "Regra principal atualizada" }); await caller.xifado.master.toggleRule({ id: ruleId }); await caller.xifado.master.removeRule({ id: ruleId }); await caller.xifado.master.setSchedule({ start: "2026-09-01T02:59:00.000Z", end: "2026-10-01T02:59:00.000Z" }); expect(state.penalties[0].visible).toBe(false); expect(state.rules[0].visible).toBe(false); expect(state.schedule.start).toContain("2026-09-01"); });
});
